### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: '/data'

### ISSUE THREAD

**Issue by YongpeiZhu** [FirasGit/medicaldiffusion#11]
I run the command and occurred the following problem:
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/medicaldiffusion/lib/python3.8/site-packages/lightning_fabric/loggers/tensorboard.py", line 201, in log_metrics
    self.experiment.add_scalar(k, v, step)
  File "/home/ubuntu/anaconda3/envs/medicaldiffusion/lib/python3.8/site-packages/lightning_fabric/loggers/logger.py", line 117, in experiment
    return get_experiment() or _DummyExperiment()
  File "/home/ubuntu/anaconda3/envs/medicaldiffusion/lib/python3.8/site-packages/lightning_utilities/core/rank_zero.py", line 32, in wrapped_fn
    return fn(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/medicaldiffusion/lib/python3.8/site-packages/lightning_fabric/loggers/logger.py", line 115, in get_experiment
    return fn(self)
  File "/home/ubuntu/anaconda3/envs/medicaldiffusion/lib/python3.8/site-packages/lightning_fabric/loggers/tensorboard.py", line 177, in experiment
    self._fs.makedirs(self.root_dir, exist_ok=True)
  File "/home/ubuntu/anaconda3/envs/medicaldiffusion/lib/python3.8/site-packages/fsspec/implementations/local.py", line 47, in makedirs
    os.makedirs(path, exist_ok=exist_ok)
  File "/home/ubuntu/anaconda3/envs/medicaldiffusion/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/home/ubuntu/anaconda3/envs/medicaldiffusion/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/home/ubuntu/anaconda3/envs/medicaldiffusion/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  [Previous line repeated 8 more times]
  File "/home/ubuntu/anaconda3/envs/medicaldiffusion/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/data'

**Comment by Meghpal** [comment]
Do you have a data folder in your root? `/data` ?

You can try to do:
```
ls /data
```

If you do you can check if the script has access to it:
```
ls -lr /
```

**Comment by zhao9chen99999** [comment]
how did you solve the problem？

**Comment by supgy** [comment]
I meet the same problem, did you solved it?

**Comment by Mrxiangli** [comment]
set the model.default_root_dir to some directory you can access
